name: Deploy JAR to AWS

on:
  workflow_dispatch: # manual trigger
  push:
    branches:
      - pr-task

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # adjust if different
          distribution: 'temurin'

      - name: Build JAR
        run: |
          cd app
          mvn clean package -DskipTests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # your region

      - name: Upload JAR to S3
        run: |
          JAR_FILE=$(ls app/target/*.jar | head -n 1)
          aws s3 cp "$JAR_FILE" s3://balteen121/ --acl bucket-owner-full-control

      # Optional: Trigger Auto Scaling Group instance refresh
      - name: Refresh ASG to redeploy new version
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name balteen121-asg \
            --preferences '{"InstanceWarmup":300,"MinHealthyPercentage":100}'
