name: Deploy JAR to S3

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'        # or your app’s version
          distribution: 'temurin'

      - name: Build JAR
        run: |
          cd app
          mvn clean package -DskipTests
          ls target  # just to verify the jar exists

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload JAR to S3
        run: |
          JAR_NAME=$(ls app/target/*.jar | xargs -n 1 basename)
          aws s3 cp ./app/target/${JAR_NAME} s3://balteen121/${JAR_NAME} --acl bucket-owner-full-control
